[Doc] Reword the section about the locale in Live Components
symfony/ux pull request #1539
Opened 2024-02-22 16:19 UTC by javiereguiluz

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Issues        | -
| License       | MIT

Context: we have a localized project that doesn't add the locale in the URL. When refreshing the page after any UX change, the local was lost.

I read the docs but I couldn't fully understand it. I thought this was only for projects that include the locale in the URLs. In any case, after asking to Kevin and Ryan, they told me that this solution also applied to my case. They were right ... so I propose a minor reword to make it more clear that this solution is for everybody that works on localized projects.

2024-02-22 20:28 UTC, kbond requested changes
Looks good! Can you remove the following line to make the CI happy?

```
.. _`localizes its URLs`: https://symfony.com/doc/current/translation/locale.html#translation-locale-url
```

2024-02-22 20:28 UTC, kbond commented on src/LiveComponent/doc/index.rst
> +the UX Live Components route definition to keep the locale between refreshes:
```suggestion
the UX Live Components route definition to keep the locale between re-renders:
```

2024-02-23 11:56 UTC, smnandre approved these changes

2024-02-23 14:41 UTC, javiereguiluz commented on src/LiveComponent/doc/index.rst
> +the UX Live Components route definition to keep the locale between refreshes:
Fixed! Thanks Kevin.

2024-02-23 14:54 UTC, kbond approved these changes

2024-02-23 14:55 UTC, kbond commented
Thank you Javier.

2024-02-23 14:55 UTC, merged