[LiveComponent] improve errors when LiveArg is missing for live action and live listener
symfony/ux pull request #1906
Opened 2024-06-10 14:46 UTC by WebMamba

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Issues        | Fix 
| License       | MIT

This PR improves the error message when a LIveArg is missing on live action or live event. Here is the new error and the previous one.

<img width="1347" alt="Capture d’écran 2024-06-10 à 16 43 38" src="https://github.com/symfony/ux/assets/32077734/8f3f7645-a4de-4405-9fd2-7fe335a00711">
<img width="1383" alt="Capture d’écran 2024-06-10 à 16 44 19" src="https://github.com/symfony/ux/assets/32077734/34271b75-a034-40ab-ab0e-7f57293c7fe0">

2024-06-10 20:37 UTC, smnandre commented on src/LiveComponent/src/EventListener/LiveComponentSubscriber.php
> +            if (str_starts_with($event->getThrowable()->getMessage(), 'Could not resolve argument $key')) {
Can we use a class/interface here?

2024-06-10 20:42 UTC, smnandre commented
What will be displayed if the LiveComponent is not tagged with controller_arguments (or does not extends AbstractController) ?

2024-06-14 20:47 UTC, smnandre commented
Hmm ok ... 

It's because of the NotTaggedControllerValueResolver registered only in debug.

We should see this message instead, already better.
<img width="1207" alt="Capture d’écran 2024-06-14 à 22 45 01" src="https://github.com/symfony/ux/assets/1359581/5bab7417-40fb-4f6a-acf3-87c3a6b45a2b">

And, guess what..... all this is related to our LiveArg implementation 🤖 

So i suggest we take some time (when we can) to make a good, stable & durable fix for LiveArg 

.. and we won't have this problem anymore :à

2025-01-05 15:30 UTC, Kocal requested changes
Checking on the exception message is a bit fragile, can't we check on the exception class name or where the extension has been thrown?

Also, tests are missing.

2025-10-09 09:39 UTC, Kocal commented
I am closing due to inactivity, feel free to re-open the PR if necessary. Thanks for the contribution!

2025-10-09 09:39 UTC, closed without merging