[Icons] Add support for int/float attribute to `Icon` component
symfony/ux pull request #2149
Opened 2024-09-11 11:46 UTC by Kocal

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Issues        | Fix #2148 
| License       | MIT

2024-09-11 21:26 UTC, smnandre commented on src/Icons/tests/Fixtures/templates/template1.html.twig
> +    <li id="fourth">{{ ux_icon('sub:check', { height: 24, width: "24" }) }}</li>
Is this valid SVG ? oO

2024-09-11 21:27 UTC, smnandre commented on src/Icons/src/Icon.php
> +            if (!\is_string($value) && !\is_bool($value) && !\is_int($value) && !\is_float($value)) {
Do you have any real-life usage for a float ? 
```suggestion
            if (!\is_string($value) && !\is_bool($value) && !\is_int($value)) {
```

2024-09-11 21:29 UTC, smnandre commented on src/Icons/src/Icon.php
> +            if (!\is_string($value) && !\is_bool($value) && !\is_int($value) && !\is_float($value)) {
You need to adjust the docblock here too. And probably on the renderer. But i'd like to have more explanation than "fix" :))

2024-09-11 21:29 UTC, smnandre requested changes
It is not a bug fix..

But i'm fully open to discuss the feature _if_ there is a real usage behind :)

2024-09-12 02:19 UTC, smnandre commented
This works already

```twig
<twig:ux:icon height="48" width="64" />
```

So the problem is when you want to pass some dynamic value (and i really would love to have an example) 

```twig
<twig:ux:icon height="48" width="{{ 64 / 2 }}" />
```


But i'm not ok to change it in Icon ... as a SVG tag does not have "float" or "int" values, but only strings.

So maybe we can (string) values in the Renderer :|

2024-09-12 06:01 UTC, smnandre commented on src/Icons/tests/Fixtures/templates/template1.html.twig
> +    <li id="fourth">{{ ux_icon('sub:check', { height: 24, width: "24" }) }}</li>
Ok so @norkunas gave me an example.... `data-id="22"` is indeed perfectly valid (and legit)

2024-09-12 06:36 UTC, Kocal commented
> This works already
> 
> ```
> <twig:ux:icon height="48" width="64" />
> ```
> 
> So the problem is when you want to pass some dynamic value (and i really would love to have an example)
> 
> ```
> <twig:ux:icon height="48" width="{{ 64 / 2 }}" />
> ```

Yes, that's what is described in issue #2148.

> But i'm not ok to change it in Icon ... as a SVG tag does not have "float" or "int" values, but only strings.

In absolute terms, all the values you pass to HTML attributes are strings, but are then interpreted specially.
For example, `<input type="range">` which accepts two attributes [`min`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#min) and [`max`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#max), you pass strings but it needs to be a (_stringified_) number.

You can do it without any issues with Vue or React/JSX: 
```vue
<input type="range" :min="1" max="120" />
```
```jsx
<input type="range" min="1" max={10} />
```

But here, we do not speak about the SVG tag but the `UX:Icon` component instead. Which IMO should behave like other `TwigComponent` and correctly auto-cast int/string values, ex:
```php
#[AsTwigComponent]
final class AutocastInt
{
    public string $min;
    public int $max;
}
```
```twig
<twig:AutocastInt min="1" max="10" />
<twig:AutocastInt :min="1" :max="10" />
<twig:AutocastInt min="{{ 1 }}" max="{{ 10 }}" />
```
which renders as expected:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/2f044364-5666-44a3-b1c9-35032da8033d">

---

Anyway, I don't really understand why do we need such this validation, can't we rely on `ComponentAttributes` and let it deal with attributes rendering?

2024-09-12 07:46 UTC, smnandre commented
> But here, we do not speak about the SVG tag but the UX:Icon component instead. Which IMO should behave like other TwigComponent and correctly auto-cast int/string values, ex:

This is not directly related to the UX:Icon `component` (that does not really exist, in fact 😓 ) ..  so we can either force the string in the Listener, in the Renderer, or ... in the Icon as you did.

But i don't want to store int as "int", but as strings in Icon attributes property.. so what do you prefer ?

2024-09-12 07:48 UTC, smnandre commented
As i said, I agree to cast it, just not internally :)

2024-09-12 17:13 UTC, smnandre commented on src/Icons/CHANGELOG.md
> +-   Fix `Icon` component to accept `integer` or `float` attributes.
```suggestion
-   Add support for `int` and `float` attribute values in `<twig:ux:icon />`.
```

2024-09-12 17:15 UTC, smnandre approved these changes

2024-09-12 17:45 UTC, smnandre commented
Thanks for fixing this bug Hugo.

2024-09-12 17:45 UTC, merged