[LiveComponent] Fix morphing for Alpine.js v3
symfony/ux pull request #2259
Opened 2024-10-11 12:53 UTC by Kobo-one

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        |  /
| License       | MIT

This PR fixes live component compatibility for Alpine v3.

Currently, the live component controller already implements the Alpine morph plugin. This works fine for Alpine v2, but since v3, the `__x` property is no longer used by Alpine. Instead, we can check for `_x_dataStack`.

Also, the morph plugin no longer requires the `__x` property; the DOM element should be used instead.

I made sure the changes support both Alpine v2 and v3.

Original implementation and issue:
- https://github.com/symfony/ux/issues/984
- https://github.com/symfony/ux/pull/1126

2024-10-11 15:14 UTC, Kocal approved these changes
LGTM

2024-10-11 15:22 UTC, smnandre approved these changes

2024-10-11 15:23 UTC, smnandre commented
Thank you @Kobo-one

2024-10-15 11:11 UTC, Kocal requested changes
Hey, I tried your patch locally on my app (the one I've used when working on https://github.com/symfony/ux/pull/1126), but I'm having an issue.

Below you will find a video of my app and some interaction with a dropdown which contains a LiveComponent inside. **I already use Alpine 3** and it works as I expect things to work, but when I test your patch, then the LiveCompoent disappears:

https://github.com/user-attachments/assets/513a0f44-a4cc-4af5-89db-7652283d2a46

Is there a bug somewhere, or is it the good behavior but I did something wrong in my app?

Thanks!

2024-10-15 12:39 UTC, Kobo-one commented
Hi, 

My current test setup uses a reversed logic; an alpine element inside of a LiveComponent. The morph is necessary to keep the alpine state when a LiveComponent re-renders with DOM changes. 

But as your video shows there might be an issue with LiveComponents inside an Alpine element. Oddly enough I also tested this and did not see any weird behaviour. Both with an alpine component surrounding a LiveComponent as well as sharing the same DOM element.

Could you share more details about how your setup is structured in Twig?

**That said, this shows the PR has a breaking change and it should not be merged (yet).**

2024-10-20 14:48 UTC, smnandre commented on src/LiveComponent/assets/dist/live_controller.js
> +                        window.Alpine.morph(fromEl.__x || fromEl, toEl);
Passing fromEl here and not fromEl.__x seems weird to me, as depending on what the window.Alpine.morph will do, the following of the code can be deeply impacted here :| 

cloneHTMLElement(fromEl) for instance would return wrong results if some morphing is done on the element before

Or am I missing something ?

2025-02-11 17:29 UTC, RobinDev commented
I get the same bug. I test the patch from @Kobo-one and it's worked for me.

So, if we use Alpine.js in a live component, it could be buggy actually. 

This patch permits to fix that bug creating a bug when using Alpine.js wrapping a live component.

Did you manage it a different way ?

2025-02-11 22:56 UTC, smnandre commented
Maybe if you guys could update this PR with a simple test covering the 2 scenarios (alpine wrapping live and vice versa)

(and when i say _test_, a clean page we can run and test in browsers would do the trick i guess)

What do you think ?

2025-02-15 18:24 UTC, Kocal commented
> I get the same bug. I test the patch from @Kobo-one and it's worked for me.
> 
> So, if we use Alpine.js in a live component, it could be buggy actually.
> 
> This patch permits to fix that bug creating a bug when using Alpine.js wrapping a live component.
> 
> Did you manage it a different way ?

@RobinDev since you have the same issue, when I wasn't able to reproduce it in https://github.com/symfony/ux/pull/2259#pullrequestreview-2368996095, could you provide use a reproducer please? 🙏🏻

2025-10-09 09:36 UTC, closed without merging

2025-10-09 09:36 UTC, Kocal commented
I am closing due to inactivity, feel free to re-open the PR if necessary. Thanks for the contribution!