[Turbo] Add `<Turbo:Frame>` component
symfony/ux pull request #2303
Opened 2024-10-25 14:49 UTC by seb-jean

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| License       | MIT

I added a `<twig:Turbo-Frame>` component.

**Simple example**

```twig
<twig:Turbo:Frame id="the_frame_id" />

{# renders as: #}
<turbo-frame id="the_frame_id"></turbo-frame>
```

**With a HTML attributes**

```twig
<twig:Turbo:Frame id="the_frame_id" loading="lazy" src="{{ path('block') }}" />

{# renders as: #}
<turbo-frame id="the_frame_id" loading="lazy" src="https://example.com/block"></turbo-frame>
```
**With content**

```twig
<twig:Turbo:Frame id="the_frame_id" src="{{ path('block') }}">
    A placeholder.
</twig:Turbo:Frame>

{# renders as: #}
<turbo-frame id="the_frame_id" src="https://example.com/block">A placeholder.
</turbo-frame>
```

2024-10-26 12:49 UTC, Kocal approved these changes
Thanks for the suggestion!
Can you update the CHANGELOG please?

2024-10-27 22:03 UTC, smnandre commented on src/Turbo/templates/components/Frame.html.twig
> +    {%- endif -%}
```suggestion
    {%- block content %}{% endblock -%}
```

Or you will render the block twice (once to test if its result is empty, once to display the result)

2024-10-27 22:04 UTC, smnandre requested changes
Little change needed in the component template

2024-10-28 19:39 UTC, smnandre approved these changes
Thank you! 

Now we need to document this new component!

2024-10-30 12:42 UTC, seb-jean commented
> Thank you!
> 
> Now we need to document this new component!

Done

2024-10-30 19:57 UTC, smnandre commented on src/Turbo/doc/index.rst
> +^^^^^^^^^^^^^
```suggestion
<twig:Turbo:Frame> Twig Component
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2024-10-30 19:57 UTC, smnandre commented on src/Turbo/doc/index.rst
> +    The `<twig:Turbo:Frame>` Twig Component was added in Turbo 2.22.
```suggestion
    The ``<twig:Turbo:Frame>`` Twig Component was added in Turbo 2.22.
```

2024-10-30 20:03 UTC, Kocal commented
PR rebased, conflicts fixed, and @smnandre comments applied 🫶

2024-10-30 20:06 UTC, Kocal commented
Thank you @seb-jean.

2024-10-30 20:06 UTC, merged

2024-10-30 20:13 UTC, seb-jean commented
> Thank you @seb-jean.

With pleasure