Fix broken Link
symfony/ux pull request #2372
Opened 2024-11-14 07:01 UTC by xDeSwa

Fix broken Link

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | Fix
| License       | MIT

2024-11-14 13:11 UTC, Kocal requested changes
Thanks you for opening a pull-request, but the correction is not good.

In fact, what happens here is that `https://github.com/symfony/ux/blob/2.x/ux.symfony.com/package.json` existed, but it has been recently modified and moved to `https://github.com/symfony/ux/blob/2.x/ux.symfony.com/assets/react/build/package.json` in a refactoring PR (#2284 and another one IIRC).

Could you please update the link to the good file?

Thanks

2024-11-14 17:01 UTC, Kocal approved these changes

2024-11-14 18:44 UTC, smnandre approved these changes

2024-11-17 09:12 UTC, Kocal commented
Thank you @xDeSwa.

2024-11-17 09:12 UTC, merged