[Translator] Handle W3C locale format on document element
symfony/ux pull request #2390
Opened 2024-11-19 13:55 UTC by aleho

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | Fix #2378
| License       | MIT

According to [W3C](https://www.w3.org/TR/html401/struct/dirlang.html#h-8.1.1
) (and [RFC1766](https://www.ietf.org/rfc/rfc1766.txt)) the valid format for language codes is "primary-code"-"subcode", but Symfony expects underscores as separator, resulting in broken translations.

This changes language codes specified in the correct format for HTML to the Symfony format when reading the "lang" attribute.

2024-11-19 19:23 UTC, Kocal requested changes
Hi @aleho, and thank you for taking the subject!

This is a direct BC break for people using `<html lang="{{ app.request.locale }}">` with a `_` inside the locale, **but** the component **is still experimental**, good news! It means that we can break things :)

However, it miss the CHANGELOG update, and we can improve the documentation a little bit.

Also, can you update the test `getLocale / default locale` to ensure that `expect(getLocale()).toEqual('fr_FR')` when `document.documentElement.lang = 'fr-FR';`?

Thanks!

2024-11-19 19:23 UTC, Kocal commented on src/Translator/doc/index.rst
> +#. Or with ``<html lang="your-locale">`` attribute (e.g., `en-US`)
To get closer to reality, I think we can modify the examples to use `app.request.locale`:
```suggestion
#. Or with ``<html data-symfony-ux-translator-locale="{{ app.request.locale }}">`` attribute (e.g., `en_US`)
#. Or with ``<html lang="{{ app.request.locale|replace({ '_': '-' }) }}">`` attribute (e.g., `en-US`)
```

2024-11-19 20:30 UTC, smnandre commented on src/Translator/doc/index.rst
> +#. Or with ``<html lang="your-locale">`` attribute (e.g., `en-US`)
Maybe use the occasion to update the previous line too ? 

```
- #. With ``setLocale('your-locale')`` from ``@symfony/ux-translator`` package
+ #. With ``setLocale('your_locale')`` from ``@symfony/ux-translator`` package
```

wdyt ?

2024-11-19 21:04 UTC, Kocal commented on src/Translator/doc/index.rst
> +#. Or with ``<html lang="your-locale">`` attribute (e.g., `en-US`)
Let's directly use a real locale, short and long forms

2024-11-20 09:31 UTC, aleho commented
> This is a direct BC break for people using `<html lang="{{ app.request.locale }}">` with a `_` inside the locale

Is it? Did I miss something? In my tests it didn't matter whether I used `de`, `de_DE` or `de-DE`, all work with this PR. (See new tests.)

What doesn't work is using `en(-|_)US` if there's no `en_US` configured in Symfony. Neither does `de(-|_)AT` if only `de` and `de_DE` are configured. (But that's unrelated to my PR, it wouldn't fallback to the available primary code before either.)


> However, it miss the CHANGELOG update

If this isn't a BC break, does it still need a changelog entry? Or can this be a bug fix?


Now with tests. Sorry about that, completely forgot to commit them.

2024-11-20 10:10 UTC, smnandre commented on src/Translator/doc/index.rst
> +#. Or with ``<html lang="{{ app.request.locale|replace({ '_': '-' }) }}">`` attribute (e.g., `de-AT` or `de` for W3C spec compliant format)
```suggestion
#. Or with ``<html data-symfony-ux-translator-locale="{{ app.request.locale }}">`` attribute (e.g., ``de_AT`` or ``de`` using Symfony locale format)
#. Or with ``<html lang="{{ app.request.locale|replace({'_': '-'}) }}">`` attribute (e.g., ``de`` or ``de-AT`` or  following HTML specifications)
```

wdyt ?

2024-11-20 10:18 UTC, smnandre commented
> If this isn't a BC break, does it still need a changelog entry? Or can this be a bug fix?

Almost a feature here :) 


```diff
# CHANGELOG

+ ## 2.22.0
+ 
+ -  Support both "fr-FR" and "fr_FR" format in html lang attribute

## 2.20.0

```

Something like this maybe ? (wording to illustrate only 😅 )

2024-11-20 13:25 UTC, Kocal commented on src/Translator/assets/test/translator.test.ts
> +            // allow format according to W3
```suggestion
            // allow format according to W3C
```

2024-11-20 13:26 UTC, Kocal approved these changes
Good to me after applying @smnandre suggestion

2024-11-20 17:13 UTC, aleho commented
@smnandre @Kocal Thanks!

2024-11-20 20:03 UTC, Kocal commented
Thank you @aleho.

2024-11-20 20:03 UTC, merged