Fix [Live] "Hooks: Handle Component Behavior" spacing issue
symfony/ux pull request #2435
Opened 2024-12-09 16:30 UTC by nehalgajjar

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | Fix #2363
| License       | MIT

## [Issue] Fix Line Break / Spacing
<img width="641" alt="image" src="https://github.com/user-attachments/assets/ee5336a2-fa1f-4f5d-a05d-5d561d5c5229">

2024-12-09 20:39 UTC, Kocal approved these changes

2024-12-10 04:45 UTC, smnandre requested changes
Good catch, but the original issue is probably due to the lack of empty line between the title and the paragraph.

2024-12-10 04:45 UTC, smnandre commented on src/LiveComponent/doc/index.rst
> +Most of the time, you'll just pass data to your components and let it handle the rest. However, if you need to do something more complex during certain stages of a component's lifecycle, you can take
```suggestion
Most of the time, you'll just pass data to your components and let it handle the
rest. However, if you need to do something more complex during certain stages of
a component's lifecycle, you can take advantage of lifecycle hooks.
```

Symfony documentation standards has line length requirements: https://symfony.com/doc/current/contributing/documentation/standards.html

Could you update the other changes to stay under 80 chars lines ? 

Thank you!

2024-12-10 05:18 UTC, smnandre commented
Also, let put this later in the documentation. It's a bit too early right now (all the concepts have not yet been explained that early)

2024-12-11 00:37 UTC, smnandre approved these changes

2024-12-11 00:38 UTC, smnandre commented
Thank you @nehalgajjar.

2024-12-11 00:38 UTC, merged