[LiveComponent] Move defaultAction validation to compiler pass
symfony/ux pull request #322
Opened 2022-05-09 13:17 UTC by norkunas

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Tickets       | N/A
| License       | MIT

Completes `todo` note which was in source code :)

2022-05-09 14:10 UTC, kbond requested changes
Awesome, thanks for doing this @norkunas! Just a rogue dump that needs to be removed :)

2022-05-09 14:10 UTC, kbond commented on src/LiveComponent/src/DependencyInjection/Compiler/ComponentDefaultActionPass.php
> +        foreach ($container->findTaggedServiceIds('twig.component') as $class => $component) {
```suggestion
        foreach ($container->findTaggedServiceIds('twig.component') as $class => $component) {
```

2022-05-09 14:11 UTC, norkunas commented on src/LiveComponent/src/DependencyInjection/Compiler/ComponentDefaultActionPass.php
> +        foreach ($container->findTaggedServiceIds('twig.component') as $class => $component) {
Oops :D

2022-05-11 20:01 UTC, weaverryan approved these changes
👏

2022-05-11 20:05 UTC, kbond approved these changes

2022-05-13 00:51 UTC, weaverryan commented
Thanks Tomas!

2022-05-13 00:51 UTC, merged