[LiveComponent] Fix calculateFingerprint with big objects
symfony/ux pull request #725
Opened 2023-03-08 11:37 UTC by LunkLoafGrumble

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Tickets       | N/A
| License       | MIT

This pull request will fix an issue for large objects (for example entities with a large relations) with in the FingerprintCalculator

While working with liveComponents I noticed my project getting slower and slower. After some digging I found out that in the calculateFingerprint function the data is serialized. When an entity with relations passes by it will serialize the entity and its child objects. This takes a considerable amount of time and is not needed.

2023-03-08 14:17 UTC, kevinmade commented
I'm having the same issue.

2023-03-08 14:32 UTC, kbond reviewed
Makes sense to me!

2023-03-08 14:32 UTC, kbond commented on src/LiveComponent/src/Util/FingerprintCalculator.php
> +    private function normalizeData(array $data): array
```suggestion
    private static function normalizeData(array $data): array
```

2023-03-08 14:43 UTC, LunkLoafGrumble commented on src/LiveComponent/src/Util/FingerprintCalculator.php
> +    private function normalizeData(array $data): array
Done

2023-03-08 14:44 UTC, kbond approved these changes

2023-03-08 14:45 UTC, kbond requested changes

2023-03-08 14:45 UTC, kbond commented on src/LiveComponent/src/Util/FingerprintCalculator.php
> +        return base64_encode(hash_hmac('sha256', serialize($this->normalizeData($data)), $this->secret, true));
```suggestion
        return base64_encode(hash_hmac('sha256', serialize(self::normalizeData($data)), $this->secret, true));
```

2023-03-08 14:45 UTC, kbond commented on src/LiveComponent/src/Util/FingerprintCalculator.php
> +                return $this->normalizeData($value);
```suggestion
                return self::normalizeData($value);
```

2023-03-08 14:51 UTC, kbond approved these changes

2023-03-08 15:13 UTC, weaverryan commented
Great catch on this!

These fingerprints need to be a deterministic string that represents "the input passed into a component" - https://github.com/symfony/ux/blob/e45a8edfcd6d6ab62248d1ffe42ef13e9dcc11b3/src/LiveComponent/src/Util/LiveControllerAttributesCreator.php#L68 - and they need to always return the same string for the same input.

If you pass an object (e.g. a `Post` entity) into a component, the `spl_object_id()` of that might be different the next time the component is re-rendered via an Ajax call, right?

I'm open to ideas on how to fix this. In practice, if we added some special code for entity objects that, if persisted, used their id instead of serializing them, that might solve things. For example, if one of the items in `$data` is a `Post` entity, then instead of serializing that or `spl_object_id()`, we use `App\Entity\Post:{THE_ID}`.

2023-03-08 15:14 UTC, kbond commented
> These fingerprints need to be a deterministic string that represents

Oops, didn't realize this. Could `spl_object_hash()` be used? I don't know if this would still have a perf problem.

2023-03-08 15:15 UTC, weaverryan commented
I think `spl_object_hash()` has the same problem - not 100% certain on that, but pretty sure.

2023-03-08 15:15 UTC, kbond commented
You're right. From php.net:

> When an object is destroyed, its hash may be reused for other objects.

2023-03-08 15:17 UTC, kbond commented
> These fingerprints need to be a deterministic string that represents "the input passed into a component" -

We should have a test to prove this behaviour.

2023-03-08 15:25 UTC, kevinmade commented
Perhaps it's an idea to add `if (\is_object($value) && method_exists($value, 'getId')) {
                return $value->getId();
            }` instead of `\is_object($value)`.

2023-03-09 14:34 UTC, kbond requested changes
@LunkLoafGrumble does this method improve the speed in your app?

Could you add a basic integration test for `FingerprintCalculator` that proves the generated fingerprint is the same two different object instances that are equal?

2023-03-09 14:34 UTC, kbond commented on src/LiveComponent/src/Util/FingerprintCalculator.php
> +        return array_map(function (mixed $value) {
Can we just call `return $this->objectNormalizer->normalize($value, context: [LiveComponentHydrator::LIVE_CONTEXT => true]);` (or inline above)?

2023-03-09 19:51 UTC, LunkLoafGrumble commented on src/LiveComponent/src/Util/FingerprintCalculator.php
> +        return array_map(function (mixed $value) {
Good suggestion. changed it.

2023-03-09 19:52 UTC, LunkLoafGrumble commented
Using objectNormalizer greatly improves the performance over just serializing the object.

2023-03-09 19:56 UTC, kbond requested changes
A few remaining minor things, then good to go by me!

2023-03-09 19:56 UTC, kbond commented on src/LiveComponent/tests/Integration/Util/FingerprintCalculatorTest.php
> +        self::assertNotEquals(
```suggestion
        self::assertNotSame(
```

2023-03-09 19:56 UTC, kbond commented on src/LiveComponent/tests/Integration/Util/FingerprintCalculatorTest.php
> +        self::assertEquals(
```suggestion
        self::assertSame(
```

2023-03-09 19:56 UTC, kbond commented on src/LiveComponent/tests/Integration/Util/FingerprintCalculatorTest.php
> +        self::assertNotEquals(
```suggestion
        self::assertNotSame(
```

2023-03-09 20:01 UTC, kbond approved these changes

2023-03-15 14:22 UTC, weaverryan commented
Let's give this version a try - thanks @LunkLoafGrumble!

2023-03-15 14:22 UTC, merged

2023-05-01 15:55 UTC, weaverryan commented
FYI - I'm reverting this in #832. But I'm hoping that it's not a problem anymore because usually zero LiveProps are used to calculate the fingerprint. But please tell me if you still have issues.