Fixing old stimulus_controller() syntax for multiple controllers
symfony/ux pull request #939
Opened 2023-06-13 14:59 UTC by weaverryan

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Tickets       | #937
| License       | MIT

I believe all other usages I'm aware of are ok.

Cheers!

2023-06-13 18:21 UTC, jmsche requested changes

2023-06-13 18:21 UTC, jmsche commented on src/Typed/doc/index.rst
> +        <body {{ stimulus_controller('mytyped'), stimulus_controller('symfony/ux-typed', {
```suggestion
        <body {{ stimulus_controller('mytyped')|stimulus_controller('symfony/ux-typed', {
```

2023-06-23 00:04 UTC, weaverryan commented on src/Typed/doc/index.rst
> +        <body {{ stimulus_controller('mytyped'), stimulus_controller('symfony/ux-typed', {
thank you for catching that :)

2023-06-23 06:54 UTC, jmsche approved these changes

2023-06-26 17:45 UTC, merged